issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fohte@11088009/spec-sync-action@1362946243:ref:refs/heads/.+$
claim_pattern:
  job_workflow_ref: ^fohte/spec-sync-action/\.github/workflows/test\.yml@[^@]+$
permissions:
  contents: write
